collections:
  research:
    output: true
    label: research
    permalink: /research/:name

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

url: "https://jinglescode.github.io"

paginate: 12
paginate_path: "/page:num/"

permalink: pretty

defaults:
  -
    scope:
      path: "/pages/research/pdfs/*"
    values:
      sitemap: false
  -
    scope:
      path: "/assets/*"
    values:
      sitemap: false
  -
    scope:
      path: "/backup/*"
    values:
      sitemap: false
