title: "Khok Hong Jing (Jingles)"
tagline: "Jingles writes about Machine Learning & Neuroscience"
description: "Jingles writes about Machine Learning & Neuroscience. Curious and inquisitive with a constant desire to learn and pioneer new uses for machine learning."
author: "Khok Hong Jing (Jingles)"
image: "https://jinglescode.github.io/assets/img/hongjing.jpeg"
social:
  links:
    - https://www.linkedin.com/in/jingles/
    - https://github.com/jinglescode/
    - https://medium.com/@jinglesnote

collections:
  research:
    output: true
    label: research
    permalink: /research/:name

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

url: "https://jinglescode.github.io"

paginate: 12
paginate_path: "/page:num/"

permalink: pretty

future: true

defaults:
  -
    scope:
      path: "/pages/research/pdfs/*"
    values:
      sitemap: false
  -
    scope:
      path: "/assets/*"
    values:
      sitemap: false
  -
    scope:
      path: "/backup/*"
    values:
      sitemap: false
