collections:
  datascience:
    output: true
    permalink: /datascience/:path/
  setup:
    output: true
    permalink: /setup/:path/
  info:
    output: true
    permalink: /info/:path/
  javascript:
    output: true
    permalink: /javascript/:path/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

url: "https://jinglescode.github.io"

paginate: 12
paginate_path: "/page:num/"

permalink: pretty

defaults:
  -
    scope:
      path: "/research/pdfs/*"
    values:
      sitemap: false
  -
    scope:
      path: "/assets/*"
    values:
      sitemap: false
  -
    scope:
      path: "/backup/*"
    values:
      sitemap: false
