title: "Raha Moosavi"
tagline: "Writes about Data science & Machine Learning"
description: "Raha writes about Data science & Machine Learning. Curious and inquisitive with a constant desire to learn and pioneer new uses for machine learning."
author: "Raha Moosavi"
image: "https://acse.github.io/assets/img/hongjing.jpeg"
social:
  links:
    - https://www.linkedin.com/in/raha-moosavi-9ba72a53/
    - https://stackoverflow.com/users/15148200/raha-moosavi
    - https://github.com/acse-srm3018
    - https://www.researchgate.net/profile/Raha-Moosavi
    - https://scholar.google.nl/citations?user=n33QYPIAAAAJ&hl=en

collections:
  research:
    output: true
    label: research
    permalink: /research/:name

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from
  
url: "https://acse-srm3018.github.io"

paginate: 21
paginate_path: "/page:num/"

permalink: pretty
# permalink: /:title

future: true
markdown:            kramdown
highlighter:         rouge

defaults:
  -
    scope:
      path: "/pages/research/pdfs/*"
    values:
      sitemap: false
  -
    scope:
      path: "/assets/*"
    values:
      sitemap: false
  -
    scope:
      path: "/backup/*"
    values:
      sitemap: false
